apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-survey-deployment
  labels:
    app: student-survey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-survey
  template:
    metadata:
      labels:
        app: student-survey
    spec:
      containers:
      - name: student-survey
        image: gcr.io/groupmicroservices/student-survey-service:v1713303370
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
